server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: pet
          uri: http://localhost:8082
          predicates:
            - Path=/pets/**, 
        - id: feed
          uri: http://localhost:8083
          predicates:
            - Path=/feedings/**, 
        - id: static
          uri: http://localhost:8084
          predicates:
            - Path=/statics/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pet
          uri: http://pet:8080
          predicates:
            - Path=/pets/**, 
        - id: feed
          uri: http://feed:8080
          predicates:
            - Path=/feedings/**, 
        - id: static
          uri: http://static:8080
          predicates:
            - Path=/statics/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
